### PR TITLE
Weather app

### PR DESCRIPTION
**Pull request by aliciapaz**
## Weather App 🌥️ 

A weather App that uses OpenWeather API to retrieve weather forecasts for any given city. 

### Main features: 
- Find a weather forecast by entering a city in the search bar and hitting "Go"
- A special icon is displayed according to the weather

### Technical specifications: 
- Use of ES6 async/await to fetch data from the OpenWeather API
- Use of `try/catch` block to handle errors 
- Use of object destructuring to handle fetched data
- Use of modules to organize the code
- Use of Webpack to bundle all modules and assets, including styles and images.

### CODE REVIEW

**Review by rukundoeric — CHANGES_REQUESTED** [review]
# Status: ♻️ CHANGES REQUIRED ♻️
_Great job guys so far 👏 💯 👍. However, there are few issues we need to address before we move on, please check the comments below._

- ### To Highlight
  - Follows gitwork-flow. 💯 
  - Codebase looks clean and professional. 💯

- ### To Improve
  - [x] [MANDATORY] App should have a toggle control to determine if the result will be shown in Celsius or Fahrenheit (There are two valid solutions: you can make two different requests for the Celsius data and the Fahrenheit data OR make only one request and use math to convert it to the other unit) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/search_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/weather-app))
  - [x] [MANDATORY] Should change its appearance based on the received data ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/appearance_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/weather-app)). For example: if the weather is rainy or cloudy, change the background accordingly. 

_Please make all the required changes before you submit another code review. If you have any problems or concerns, you can reach out to me on Slack: Rukundo Eric 🚀 . I wish you all the very best 🥇_

### _Keep working hard._
### _Happy Coding😃_
-----------------------------------------------------------------------------------------------------------------------------------------
**Regards,
[Rukundo Eric](https://rukundo-eric.herokuapp.com/) ,
[LinkedIn](https://www.linkedin.com/in/rukundo-eric/), 
Slack: Rukundo Eric**

**Comment by aliciapaz** [comment]
## Added the following features: 
- A different background is displayed according to the weather
- The user can choose between °F or °C when searching for a location's forecast

**Review by NtwaliHeritier — CHANGES_REQUESTED** [review]
### **STATUS: CHANGES REQUESTED🛑🛑🛑**

Hello @aliciapaz 
Great work making the requested changes.
However, let's make a final change and get it approved.

[REQUIRED]: Make the transition from Celsius to Fahrenheit using a toggle button not a dropdown.

That's it.

Make the requested changes and ask for another review👌👍

Happy coding💻💻

**Comment by aliciapaz** [comment]
Changed dropdown to toggle button. 
image
Thank you!

**Review by bellom — CHANGES_REQUESTED** [review]
## Hi @aliciapaz :clap: 

**Great work making `almost` all the necessary corrections from the previous review.**

# Status: Changes Required! ♻️ 

**_1. Kindly double-check your live demo link, seems broken._**(I couldn't search for any city, the app threw an error
image
)
**_2. Yes, you added the toggle feature but seems not to work properly._**(I couldn't see the toggle result in C.)
image


**Could it be from my end 🤔** 


### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

**Comment by aliciapaz** [comment]
## Improvements made:
- Now the toggle °C/°F works both when sending the request and once the forecast is displayed
- Fix live demo

**Review by uche-inyama — APPROVED** [review]
## Approved

### Hi Alicia :slightly_smiling_face: 

We are good here, go ahead with your next task.


### Have a great day :wave: 

#### ``` Uchechukwu Henry Inyama ```

**Pull request merged**
